name: Gameboy
main: me.kyllian.gameboy.GameboyPlugin
author: Kyllian
version: ${project.version}
api-version: 1.13
softdepend:
  - ProtocolLib
depend: [DecentHolograms]

commands:
  gameboy:
    usage: /<command>
    description: Base command of the plugin
    aliases:
      - gb